### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by bartoszmaka** [bartoszmaka/rails-lottery-app#1]
### Lottery Platform
- [x] roles should be defined by _rolify_
- [x] to capture emails in development use _latter_opener_web_
- [x] for authentication use _devise_

#### Client Part

*   on main page see all the items avaialble to bid
    - [x] can search item by name **ransack**
    - [x] 6 items per page **kaminari**
*   item datails page should display
    - [x] basic info about item
    - [x] all the bidders
*   logged user can
    - [x] bid any item
    - [x] see items that he/she win/loose/is bidding
    - [x] edit profile (including avatar upload)

#### Administrate Part

*   can create items (each item have name, uploaded picture) _carrierwave_
    - [x] item can be edited
    - [x] item can be deleted (only if there is no bidder)
*   can run draw
    - [x] if at least two bidders are present
    - [x] one person that win the draw should get email

#### Refactoring

- [x] use _rubocop_ to align code styles
- [x] move all the draw logic into service object
- [x] rewrite forms using _simpleform_
- [x] rewrite your controllers using _decent_exposure_
- [x] improve your views using _draper_ (use decorate option from decent_exposure)
- [ ] improve your controllers using _decent_decoration_
- [ ] add nice urls names using _friendly_id_
- [x] prapare fake data from console using ffaker
- [ ] copy database using pgadmin, and leave main one untouched
- [ ] refactor service object using _active_interaction_
- [x] use _slim_
- [ ] write specs for controllers and service objects using rspec

#### style your app (optional)

- [ ] review [https://getmdl.io/started/index.html](https://getmdl.io/started/index.html)
- [ ] use [https://github.com/rubysamurai/material_design_lite-sass](https://github.com/rubysamurai/material_design_lite-sass)
